### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by friesga** [hackyourlife/lsi-11#1]
Hi,

Recently I found your lsi-11 simulator on github. I was amazed that with such a small amount of code a lsi-11 simulator could be written and was impressed with the structured, object-oriented way the code was set up.

I noticed that the code and readme files don't mention a license. Would you be willing to make this code open source and provide it with an (open source) license?

Best regards,

Jos

**Comment by hackyourlife** [comment]
Ah yeah, I forgot to add a license, so I guess I'll just put it under GPLv3.

Keep in mind that this version of the interpreter here still has two problems:
- one bit is off by one in the BDV11 module for the LTC ⇒ PDP-11 software won't activate the LTC properly because the BDV11 code checks the wrong bit
- trap handling is somewhat broken, which would be noticeable if the LTC was properly activated by e.g. RT-11. This can cause traps to be "lost" and as a result hang RT-11 since it's then waiting for e.g. a console interrupt that won't ever arrive.

I fixed these bugs over the years, but in a currently private fork, which also got most of the object orientation removed as well as a reorganized KD11CPUStep function for performance reasons. This private fork currently runs on an STM32F030 microcontroller (48MHz ARM Cortex-M0, 8kB RAM) with an external SPI SRAM chip. It also has an incomplete RL02 implementation which doesn't pass the diagnostics yet because of timings that aren't emulated, but it *does* boot the latest RT-11. I guess I could publish that fork too (and/or backport the bugfixes into this project here).

**Comment by friesga** [comment]
Thank you for drawing my attention to these points. I managed to boot XXDP and execute the VKABB0, VKADC0 and VKAHA1 diagnostics I found somewhere on the internet, but didn't yet boot RT-11 as I couldn't find suitable RX01 RT-11 images. Could you point me to a source for the RT-11SB V05.07 images you mention in the README?

I'm currently following a C++ course and I would like to use the lsi-11 software as a case study for conversion to and extension of the sources in C++. And ultimately it would be nice to develop an alternative for the simh PDP-11 simulator. simh is a great piece of software, but its architecture could be improved and in general the sources need restructuring. It would be wise to start with a clean sheet and the lsi-11 software perhaps could serve that purpose.

**Comment by hackyourlife** [comment]
This is the code I used to test the interpreter, including the failing floating point tests: [lsi-11-code.tar.gz](https://github.com/hackyourlife/lsi-11/files/7848996/lsi-11-code.tar.gz)
I cannot remember where I got the RT-11 floppy image, but it's included in the archive. Otherwise you *could* create a suitable RX02 floppy image yourself using e.g. simh and an RT-11 distribution disk.

You can find more diagnostics in the [PDP-11 Diagnostic Database](http://retrocmp.com/images/stories/joerg/pdp11_diagnostic_database//////devices.html), including microfiche scans to understand diagnostic failures.

I just backported the relevant fixes to get the trap handling right and to properly enable the LTC ⇒ the `TIME` command in RT-11 should have a clock that doesn't hang at zero, but it's slower than it should be, probably because of 50Hz vs 60Hz LTC.

**Comment by friesga** [comment]
Thanks for the updates and the links! I'll c;lose this issue for now and come back to you in case I have more questions.
